[font]
size = 10

[font.normal]
#family = "Comic Shanns Regular"
#family = "Ac437 IBM Model3x Alt2"

family = "LigaMonacoNerdFont"

[general]
import = [
    "~/.config/alacritty/themes/themes/hyper.toml",
]

[colors]
cursor = { text = "#84c1db", cursor = "#84c1db" }

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "block"
