[font]
size = 10

[font.normal]
family = "Comic Shanns Mono NerdFont"
#family = "Ac437 IBM Model3x Alt2"
#family = "DejaVu Sans Mono"
#family = "LigaMonacoNerdFont"

[general]
import = [
    "~/.config/alacritty/themes/themes/hyper.toml",
]

[colors]
cursor = { text = "#84c1db", cursor = "#84c1db" }

[cursor.style]
blinking = "Always"
shape = "block"
